# Generated by Django 2.2.1 on 2019-07-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('available', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
